/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lhd_ccalljava_JNIS */

#ifndef _Included_com_lhd_ccalljava_JNIS
#define _Included_com_lhd_ccalljava_JNIS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lhd_ccalljava_JNIS
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lhd_ccalljava_JNIS_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_lhd_ccalljava_JNIS
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lhd_ccalljava_JNIS_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_lhd_ccalljava_JNIS
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lhd_ccalljava_JNIS_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_lhd_ccalljava_JNIS
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lhd_ccalljava_JNIS_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
